// <auto-generated />
using Contracting.Infrustructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace Contracting.Infrustructure.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260618000001_FixClientStatusEnumValues")]
    partial class FixClientStatusEnumValues
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
            // Data-only migration — no schema changes.
            // BuildTargetModel is not exercised at runtime by MigrateAsync().
        }
    }
}
